### ISSUE TITLE
Config mistake

### ISSUE THREAD

**Issue by peoplehlj** [guoger/fabric-deployment#1]
Hi, guoger,

The 217 line of file fabric-deployment/multi-orderer-kafka/dc-orderer-kafka.yml
`
volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer1.org0.example.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer1.org0.example.com/tls:/etc/hyperledger/fabric/tls
`

maybe you made some mistake, "**org1**.example.com->peer1.**org0**.example.com" is not matched, it will cause peer1.org0 node exiting after deploying. Please take a look or I can raise a pull request, thanks.

**Comment by guoger** [comment]
Thank you so much for raising the issue! I've corrected it. Feel free to submit a PR should you find any potential problems!

**Comment by peoplehlj** [comment]
By the way @guoger , did fabric-v1.0.0-alpha support to deploy orderer based on kafka?
